### ISSUE TITLE
Issue Manually Installing

### ISSUE THREAD

**Issue by zielOS** [allusive-dev/picom#2]
when I run 
`
meson setup --buildtype=release build`

I get the following error:
`ERROR: File media/icons/48x48/compton.png does not exist.`

Can you post a guide non-arch users if the installation steps differ from other picom forks?

**Comment by Nehemias44** [comment]
The media directory with the icon images is missing. You can copy it from other repositories or comment the lines in meson.build.

**Comment by zielOS** [comment]
I also wanted to ask. Did you make any changes from pijulius's version, or was this repo just created to get pijulius-picom back in the AUR? @allusive-dev

**Comment by allusive-dev** [comment]
Oh lmao hi guys.
So i deleted the media directory thinking it was not important. Looks like it was.
I will bring it back in now.

**Comment by allusive-dev** [comment]
Everything should be working now, let me know if there are any more issues.

**Comment by allusive-dev** [comment]
> I also wanted to ask. Did you make any changes from pijulius's version, or was this repo just created to get pijulius-picom back in the AUR? @allusive-dev

It is basically just to get pijulius back on the AUR.
But I might make a few 'quality of life' changes to improve the efficiency/usability of the package.
